spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      auto-index-creation: true
      uri: ${MONGO_URI}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

lotto:
  number-generator:
    lotteryRunOccurrencesCron: "0 0 11 * * 6" # every Saturday at 11:00
    facade:
      count: 25
      lowerBand: 1
      upperBand: 99
    http:
      client:
        config:
          uri: http://ec2-3-120-147-150.eu-central-1.compute.amazonaws.com
          port: 9090
          connectionTimeout: 5000
          readTimeout: 5000
  result-checker:
    resultCheckOccurrencesCron: "0 55 11 * * 6" # every Saturday at 11:55