spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: ${MONGO_URI}

lotto:
  number-generator:
    lotteryRunOccurrencesCron: "0 0 12 * * 6" # every Saturday at 12:00
    facade:
      count: 25
      lowerBand: 1
      upperBand: 99
    http:
      client:
        config:
          uri: http://ec2-3-120-147-150.eu-central-1.compute.amazonaws.com
          port: 9090
          connectionTimeout: 5000
          readTimeout: 5000