spring:
  cache:
    type: redis
    redis:
      time-to-live: PT60M
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      auto-index-creation: true
      uri: ${MONGO_URI}
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

lotto:
  number-generator:
    lotteryRunOccurrencesCron: "0 0 11 * * 6" # every Saturday at 11:00
    facade:
      count: 25
      lowerBand: 1
      upperBand: 99
    http:
      client:
        config:
          uri: http://ec2-3-120-147-150.eu-central-1.compute.amazonaws.com
          port: 9090
          connectionTimeout: 5000
          readTimeout: 5000
  result-checker:
    resultCheckOccurrencesCron: "0 55 11 * * 6" # every Saturday at 11:55

auth:
  jwt:
    expirationDays: 30
    secret: ${JWT_SECRET}
    issuer: lotto-backend
